### ISSUE TITLE
Wrong error message on malformed transaction

### ISSUE THREAD

**Issue by pjc0247** [klaytn/caver-js#147]
**Describe the bug**

```
 Error: Only Legacy transactions can be signed on a Klaytn node!
```

**How to reproduce**
There are two ways to reproduce this bug:

* Works perfrect with attached code (may occurs an error since the account does not have any KLAY)
* Case1: Change `feePayer` to `        feePayer: '0xad7c07eab1e56fbbb976fd5377e5088ec5528cd9'`
* Case2: Uncomment `//gasPrice: '999999999999999',`

**Expected behavior**
The error message should indicate exactly what went wrong.

**Attachments**

```
"caver-js": {
      "version": "1.2.0",
```
```js
const Caver = require('caver-js');

const caver = new Caver('https://api.baobab.klaytn.net:8651/');
const cred = require('./cred.json');

caver.klay.getNodeInfo().then(console.log);

caver.klay.accounts.wallet.add('0x5849a0f62008833b708af0bf4886e5deec0ea51bb405bf02a7ed79d4c43e5797');
caver.klay.accounts.wallet.add({
    address: "0x48649c3beb3e5abf532b0626ce72c27cb64e012f",
    privateKey: "0x7b04975dea529019127697fb267a72e2bb3c26c3e85ae358864baa84a2b56d47"
});

const contract = new caver.klay.Contract(require('./abi.json'), '0xcd7589F4641B6d7f7f9ab08bA1d4fB5985658A0a', {
    from: cred.address,
    gasPrice: '25000000000'
});


async function createTx(tx) {
    const account = caver.klay.accounts.wallet[0];
    tx.from = account.address;
    console.log(account.address);
    const signed = await account.signTransaction(tx);
    console.log(signed);
    return signed.rawTransaction;
}

async function test() {
    const input = contract.methods.voteMob("test", 0, 0).encodeABI();
    const tx = await createTx({
        type: 'FEE_DELEGATED_SMART_CONTRACT_EXECUTION',
        to: '0xcd7589F4641B6d7f7f9ab08bA1d4fB5985658A0a',
        //gasPrice: '999999999999999',
        value: '0',
        data: input,
        gas: 900000
    });

    const resp = await caver.klay.sendTransaction({
        senderRawTransaction: tx.toString(),
        feePayer: '0x48649c3beb3e5abf532b0626ce72c27cb64e012f',
    });

    console.log(resp);
}

test();
```

**Comment by kjhman21** [comment]
@pjc0247 Thanks for the report. Below could be answers for your problems.

1. you should set the wallet account first using `caver.klay.accounts.wallet.add` to use `0xad7c07eab1e56fbbb976fd5377e5088ec5528cd9` as a fee payer. Like below:
```
caver.klay.accounts.wallet.add({
    address: "0xad7c07eab1e56fbbb976fd5377e5088ec5528cd9",
    privateKey: "0x7b04975dea529019127697fb267a72e2bb3c26c3e85ae358864baa84a2b56d47"
});
```

To interpret the error `Error: Only Legacy transactions can be signed on a Klaytn node!`,
caver.klay.sendTransaction() tries to use the caver's wallet first. If it does not exist in the caver's wallet,
caver tries to use the node wallet on 'https://api.baobab.klaytn.net:8651/'. As you can see, the node wallet does not support signing for Klaytn transaction types for now. That's why you saw that error.


2. The Klaytn mainnet, Cypress, does not allow arbitrary gas price values. It is fixed to 25 ston. Refer to https://docs.klaytn.com/bapp/sdk/caver-js#caution-when-sending-a-transaction-to-klaytn

If these does not solve your problems, please let me know. Thanks.

**Comment by pjc0247** [comment]
@kjhman21 Thanks for the reply, however this issue is not about my code but wrong indicated error message. This may confuse developers.

**Comment by kjhman21** [comment]
@pjc0247 I got it. I think all the errors caused by the first problem: unknown private key in the caver wallet. We will add more messages to the error string. Thanks. 

cc @jimni1222
