### ISSUE TITLE
Is there a way to get transaction list of a smart contract?

### ISSUE THREAD

**Issue by miraten** [klaytn/caver-js#318]
I want to get transaction list of a smart contract.
As I know, there is no the exact API to get it.

Is there any plan to add new API to support it?

Please guide or suggest how to get it.

**Comment by kjhman21** [comment]
Hi, @miraten. Thanks for filing an issue.

Do you want to get a list of transactions executing a specific smart contract using caver-js?
I'm not sure, but I think this is what you are looking for.
https://scope.klaytn.com/account/0x2e160a2b643c630e540243725764112f1bfdb1b3

Since this kinds of information is not stored in the blockchain data, caver-js cannot provide such data.

If I got it wrong, please let me know. Thanks again. :)

**Comment by miraten** [comment]
Hi, @kjhman21.

I am aware of the page you linked.

I wanted to get it by API method call. 

Thanks anyway.

**Comment by kjhman21** [comment]
@miraten 
If we do that in caver-js, we need to maintain a database somehow in caver-js. We do not have such a plan currently. Sorry for that.
